export { default as AboutPage } from './AboutPage'
export { default as ClientApp } from './ClientApp'
export { default as GetStarted } from './GetStarted'
export { default as Home } from './Home'
export { default as WhoWeServe } from './WhoWeServe'
export { default as FlexibleContent } from './FlexibleContent'